### ISSUE TITLE
AOT error

### ISSUE THREAD

**Issue by farhantriofani** [danielgatis/rembg#110]
When I just write rembg in cmd, it comes with this error

Failed to import ahead-of-time-compiled modules.
This is expected on first import.
Compiling modules and trying again.
This might take a minute.
Traceback (most recent call last):
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\pymatting_aot\cc.py", line 36, in <module>
    import pymatting_aot.aot
ModuleNotFoundError: No module named 'pymatting_aot.aot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Farhan Triofani\AppData\Local\Programs\Python\Python38\Scripts\rembg.exe\__main__.py", line 4, in <module>
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\rembg\cmd\cli.py", line 9, in <module>
    from ..bg import remove
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\rembg\bg.py", line 6, in <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\pymatting\__init__.py", line 2, in <module>
    import pymatting_aot.cc
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\pymatting_aot\cc.py", line 54, in <module>
    compile_modules()
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\pymatting_aot\cc.py", line 8, in compile_modules
    cc = CC("aot")
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\numba\pycc\cc.py", line 65, in __init__
    self._toolchain = Toolchain()
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\numba\pycc\platform.py", line 78, in __init__
    self._raise_external_compiler_error()
  File "c:\users\farhan triofani\appdata\local\programs\python\python38\lib\site-packages\numba\pycc\platform.py", line 121, in _raise_external_compiler_error
    raise RuntimeError(msg)
RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. Cannot find suitable msvc.

Any solution?

**Comment by peace20162** [comment]
https://visualstudio.microsoft.com/downloads/?utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=button+cta&utm_content=download+vs2019+rc     
download this and install c++ environment.
 it solved this problem for me.

**Comment by danielgatis** [comment]
https://github.com/danielgatis/rembg/issues/35
