### ISSUE TITLE
Remove the background from a local file not working

### ISSUE THREAD

**Issue by Chiragrchopra** [danielgatis/rembg#111]
command: rembg -o path/to/output.png path/to/input.png

error: 
Traceback (most recent call last):
  File "c:\users\chirag\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\chirag\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chirag\AppData\Local\Programs\Python\Python39\Scripts\rembg.exe\__main__.py", line 4, in <module>
  File "c:\users\chirag\appdata\local\programs\python\python39\lib\site-packages\rembg\cmd\cli.py", line 9, in <module>
    from ..bg import remove
  File "c:\users\chirag\appdata\local\programs\python\python39\lib\site-packages\rembg\bg.py", line 4, in <module>
    import numpy as np
ValueError: source code string cannot contain null bytes

**Comment by wallacesilva** [comment]
Can you add these images here, please?
