### ISSUE TITLE
"Trimap did not contain foreground values"

### ISSUE THREAD

**Issue by tjnewton** [danielgatis/rembg#116]
I get an error when using rembg on the image hosted [here](https://github.com/tjnewton/computer-vision/blob/main/a.png). It outputs a file when alpha matting is not used, but if I specify to use alpha matting I get the following error:

```
Traceback (most recent call last):
  File "/Users/human/opt/anaconda3/envs/cv/bin/rembg", line 8, in <module>
    sys.exit(main())
  File "/Users/human/opt/anaconda3/envs/cv/lib/python3.8/site-packages/rembg/cmd/cli.py", line 146, in main
    remove(
  File "/Users/human/opt/anaconda3/envs/cv/lib/python3.8/site-packages/rembg/bg.py", line 95, in remove
    cutout = alpha_matting_cutout(
  File "/Users/human/opt/anaconda3/envs/cv/lib/python3.8/site-packages/rembg/bg.py", line 54, in alpha_matting_cutout
    alpha = estimate_alpha_cf(img_normalized, trimap_normalized)
  File "/Users/human/opt/anaconda3/envs/cv/lib/python3.8/site-packages/pymatting/alpha/estimate_alpha_cf.py", line 51, in estimate_alpha_cf
    is_fg, is_bg, is_known, is_unknown = trimap_split(trimap)
  File "/Users/human/opt/anaconda3/envs/cv/lib/python3.8/site-packages/pymatting/util/util.py", line 495, in trimap_split
    raise ValueError(
ValueError: Trimap did not contain foreground values (values >= 0.900000)
```

What's happening here?

**Comment by danielgatis** [comment]
fix already in master. tks.

**Comment by minkvirparia** [comment]
@danielgatis I am also facing error while using your alpha matting function for my work. Can you please tell me the exact solution to resolve this error ?
