### ISSUE TITLE
Recompiling modules failed with exit status 1104

### ISSUE THREAD

**Issue by 3XH6R** [danielgatis/rembg#119]
Recompiling modules because they are out of date.
This might take a minute.
Traceback (most recent call last):
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\distutils\_msvccompiler.py", line 497, in link
    self.spawn([self.linker] + ld_args)
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\distutils\_msvccompiler.py", line 507, in spawn
    return super().spawn(cmd)
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\ccompiler.py", line 88, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\ccompiler.py", line 171, in CCompiler_spawn
    raise DistutilsExecError('Command "%s" failed with exit status %d%s' %
distutils.errors.DistutilsExecError: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\3xh6r\appdata\local\programs\python\python39\libs /LIBPATH:c:\users\3xh6r\appdata\local\programs\python\python39\PCbuild\amd64 /LIBPATH:c:\\users\\3xh6r\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 python39.lib msvcrt.lib npymath.lib /EXPORT:PyInit_aot C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\aot.cp39-win_amd64.o C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\pycc\modulemixin.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\cext\dictobject.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\cext\listobject.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\cext\utils.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\pycc\../core/runtime/nrt.obj /OUT:c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\pymatting_aot\aot.cp39-win_amd64.pyd /IMPLIB:C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\aot.cp39-win_amd64.lib" failed with exit status 1104

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\3XH6R\AppData\Local\Programs\Python\Python39\Scripts\rembg.exe\__main__.py", line 4, in <module>
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\rembg\cmd\cli.py", line 9, in <module>
    from ..bg import remove
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\rembg\bg.py", line 6, in <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\pymatting\__init__.py", line 2, in <module>
    import pymatting_aot.cc
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\pymatting_aot\cc.py", line 42, in <module>
    compile_modules()
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\pymatting_aot\cc.py", line 18, in compile_modules
    cc.compile()
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\pycc\cc.py", line 224, in compile
    self._toolchain.link_shared(output_dll, objects,
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\pycc\platform.py", line 153, in link_shared
    self._compiler.link(CCompiler.SHARED_OBJECT, objects,
  File "c:\users\3xh6r\appdata\local\programs\python\python39\lib\distutils\_msvccompiler.py", line 499, in link
    raise LinkError(msg)
distutils.errors.LinkError: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\3xh6r\appdata\local\programs\python\python39\libs /LIBPATH:c:\users\3xh6r\appdata\local\programs\python\python39\PCbuild\amd64 /LIBPATH:c:\\users\\3xh6r\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 python39.lib msvcrt.lib npymath.lib /EXPORT:PyInit_aot C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\aot.cp39-win_amd64.o C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\pycc\modulemixin.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\cext\dictobject.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\cext\listobject.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\cext\utils.obj C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\numba\pycc\../core/runtime/nrt.obj /OUT:c:\users\3xh6r\appdata\local\programs\python\python39\lib\site-packages\pymatting_aot\aot.cp39-win_amd64.pyd /IMPLIB:C:\Users\3XH6R\AppData\Local\Temp\pycc-build-aot-92b_119q\aot.cp39-win_amd64.lib" failed with exit status 1104

Python 3.9.6
Visual Studio 2019 | MSVC v142 | Windows 10 SDK (10.0.19041.0)
Windows 10 x64

It worked before but rembg stopped working recently then this happened while trying to recompile.

**Comment by 3XH6R** [comment]
deleted %localappdata%\programs\python and reinstalled.
seems to be working.
