### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by muhammadalised** [danielgatis/rembg#154]
Whenever I try to run the rembg using PIL I get the following error:

Downloading u2net.pth to /home/artellisys-ai/.u2net: 3.21kiB [00:00, 4.95MiB/s]
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    result = remove(f)
  File "/home/artellisys-ai/Desktop/bgrem-project/venv/lib/python3.8/site-packages/rembg/bg.py", line 90, in remove
    model = get_model(model_name)
  File "/home/artellisys-ai/Desktop/bgrem-project/venv/lib/python3.8/site-packages/rembg/bg.py", line 78, in get_model
    return detect.load_model(model_name="u2net")
  File "/home/artellisys-ai/Desktop/bgrem-project/venv/lib/python3.8/site-packages/rembg/u2net/detect.py", line 113, in load_model
    torch.load(
  File "/home/artellisys-ai/Desktop/bgrem-project/venv/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/artellisys-ai/Desktop/bgrem-project/venv/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

I am using a .jpg image
Any help please?

**Comment by muhammadalised** [comment]
Hi @patstg, Thanks a lot for your help, it works perfectly now. It seems that model was not properly downloaded via code so I downloaded it manually and put it in the .unet folder.
