### ISSUE TITLE
Hangs on windows "recompiling modules" 

### ISSUE THREAD

**Issue by audas** [danielgatis/rembg#156]
I had installed and was working - then tried the fork for video and it conflicted with Numpy.
Uninstalled everything and reinstalled but now get the following message

"Recompiling modules because they are out of date.
This might take a minute."

And can progress no further.

Any ideas.

**Comment by audas** [comment]
I have uninstalled python3.8 and installed 3.8.7 
installed build tools 2017
down graded numpy to 1.20.0

but still get the same errors

Any help appreciated - this WAS definitely working.

Recompiling modules because they are out of date.
This might take a minute.
Traceback (most recent call last):
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 501
, in link
    self.spawn([self.linker] + ld_args)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 511
, in spawn
    return super().spawn(cmd)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\distutils\ccompil
er.py", line 90, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\distutils\ccompil
er.py", line 173, in CCompiler_spawn
    raise DistutilsExecError('Command "%s" failed with exit status %d%s' %
distutils.errors.DistutilsExecError: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildToo
ls\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,I
D=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\MyName\AppData\Local\Programs\Python\Python38\libs /LIBPATH:C:\Use
rs\MyName\AppData\Local\Programs\Python\Python38\PCbuild\amd64 /LIBPATH:C:\\Users\\MyName\\AppData\\Lo
cal\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:C:\Program Files (x86)\Micr
osoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64 /LIBPATH:C:\Program Files (x86)\Wind
ows Kits\10\lib\10.0.17763.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\
x64 python38.lib msvcrt.lib npymath.lib /EXPORT:PyInit_aot C:\Users\MyName\AppData\Local\Temp\pycc-build
-aot-ootjwtom\aot.cp38-win_amd64.o C:\Users\MyName\AppData\Local\Temp\pycc-build-aot-ootjwtom\Users\SamR
olfe\AppData\Roaming\Python\Python38\site-packages\numba\pycc\modulemixin.obj C:\Users\MyName\AppData\Lo
cal\Temp\pycc-build-aot-ootjwtom\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\cext\d
ictobject.obj C:\Users\MyName\AppData\Local\Temp\pycc-build-aot-ootjwtom\Users\MyName\AppData\Roaming\
Python\Python38\site-packages\numba\cext\listobject.obj C:\Users\MyName\AppData\Local\Temp\pycc-build-ao
t-ootjwtom\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\cext\utils.obj C:\Users\SamR
olfe\AppData\Local\Temp\pycc-build-aot-ootjwtom\Users\MyName\AppData\Roaming\Python\Python38\site-packag
es\numba\pycc\../core/runtime/nrt.obj /OUT:C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\si
te-packages\pymatting_aot\aot.cp38-win_amd64.pyd /IMPLIB:C:\Users\MyName\AppData\Local\Temp\pycc-build-a
ot-ootjwtom\aot.cp38-win_amd64.lib" failed with exit status 1104

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "removebg.py", line 1, in <module>
    from rembg.bg import remove
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\site-packages\rembg\bg.py", line 6, i
n <module>
    from pymatting.alpha.estimate_alpha_cf import estimate_alpha_cf
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\site-packages\pymatting\__init__.py",
 line 2, in <module>
    import pymatting_aot.cc
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\site-packages\pymatting_aot\cc.py", l
ine 42, in <module>
    compile_modules()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\site-packages\pymatting_aot\cc.py", l
ine 18, in compile_modules
    cc.compile()
  File "C:\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\core\compiler_lock.py", line
 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\pycc\cc.py", line 224, in co
mpile
    self._toolchain.link_shared(output_dll, objects,
  File "C:\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\pycc\platform.py", line 153,
 in link_shared
    self._compiler.link(CCompiler.SHARED_OBJECT, objects,
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\distutils\_msvccompiler.py", line 503
, in link
    raise LinkError(msg)
distutils.errors.LinkError: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Too
ls\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANI
FESTUAC:NO /LIBPATH:C:\Users\MyName\AppData\Local\Programs\Python\Python38\libs /LIBPATH:C:\Users\SamRol
fe\AppData\Local\Programs\Python\Python38\PCbuild\amd64 /LIBPATH:C:\\Users\\MyName\\AppData\\Local\\Prog
rams\\Python\\Python38\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:C:\Program Files (x86)\Microsoft Vis
ual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\
10\lib\10.0.17763.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x64 pytho
n38.lib msvcrt.lib npymath.lib /EXPORT:PyInit_aot C:\Users\MyName\AppData\Local\Temp\pycc-build-aot-ootj
wtom\aot.cp38-win_amd64.o C:\Users\MyName\AppData\Local\Temp\pycc-build-aot-ootjwtom\Users\MyName\AppD
ata\Roaming\Python\Python38\site-packages\numba\pycc\modulemixin.obj C:\Users\MyName\AppData\Local\Temp\
pycc-build-aot-ootjwtom\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\cext\dictobject
.obj C:\Users\MyName\AppData\Local\Temp\pycc-build-aot-ootjwtom\Users\MyName\AppData\Roaming\Python\Py
thon38\site-packages\numba\cext\listobject.obj C:\Users\MyName\AppData\Local\Temp\pycc-build-aot-ootjwto
m\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\cext\utils.obj C:\Users\MyName\AppD
ata\Local\Temp\pycc-build-aot-ootjwtom\Users\MyName\AppData\Roaming\Python\Python38\site-packages\numba\
pycc\../core/runtime/nrt.obj /OUT:C:\Users\MyName\AppData\Local\Programs\Python\Python38\lib\site-packag
es\pymatting_aot\aot.cp38-win_amd64.pyd /IMPLIB:C:\Users\MyName\AppData\Local\Temp\pycc-build-aot-ootjwt
om\aot.cp38-win_amd64.lib" failed with exit status 1104

**Comment by audas** [comment]
Required completely uninstalling python and removing the folder - re-install.

Used old version of pytorch (recommended version)

Downgrade numpy 1.19.0

install specific version of llvmlite

lastest community version of visual studio
