### ISSUE TITLE
How to use cpu while having cuda_path

### ISSUE THREAD

**Issue by Michaelwhite34** [danielgatis/rembg#199]
D:\rembg-main\rembg-main>rembg p .\examples .\output
2022-03-07 22:17:36.2027839 [E:onnxruntime:Default, provider_bridge_ort.cc:995 onnxruntime::ProviderLibrary::Get] LoadLibrary failed with error 126 "The specified module could not be found." when trying to load "d:\python39\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
2022-03-07 22:17:36.2031703 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:509 onnxruntime::python::CreateExecutionProviderInstance] Failed to create TensorrtExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#requirements to ensure all dependencies are met.
2022-03-07 22:17:36.2766561 [E:onnxruntime:Default, provider_bridge_ort.cc:995 onnxruntime::ProviderLibrary::Get] LoadLibrary failed with error 126 "The specified module could not be found." when trying to load "d:\python39\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
Traceback (most recent call last):
  File "d:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python39\Scripts\rembg.exe\__main__.py", line 7, in <module>
  File "d:\python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "d:\python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "d:\python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\python39\lib\site-packages\rembg\cli.py", line 156, in p
    session = ort_session(model)
  File "d:\python39\lib\site-packages\rembg\detect.py", line 36, in ort_session
    return ort.InferenceSession(str(path), providers=ort.get_available_providers())
  File "d:\python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "d:\python39\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 379, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:531 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

**Comment by danielgatis** [comment]
There are 2 versions of this library. You need to choose one to install before running it.

https://github.com/danielgatis/rembg#installation
