### ISSUE TITLE
A error removing the background from all images in a folder

### ISSUE THREAD

**Issue by qwerty-qwerty1** [danielgatis/rembg#220]
I have used this command `rembg -p C:\Users\chara\Downloads\images C:\Users\chara\Downloads\Remove`, and I am getting this error
![image](https://user-images.githubusercontent.com/91939399/164164254-c0640e64-377d-4fe8-80d3-32b5d314c6e8.png)

`PS C:\Users\chara> rembg -p C:\Users\chara\Downloads\images C:\Users\chara\Downloads\Remove
C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
Downloading u2net.pth to C:\Users\chara\.u2net: 2.16kiB [00:00, 1.10MiB/s]           | 0/10 [00:00<?, ?it/s]
  0%|                                                                                | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\Scripts\rembg.exe\__main__.py", line 7, in <module>
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\site-packages\rembg\cmd\cli.py", line 132, in main
    remove(
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\site-packages\rembg\bg.py", line 90, in remove
    model = get_model(model_name)
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\site-packages\rembg\bg.py", line 78, in get_model
    return detect.load_model(model_name="u2net")
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\site-packages\rembg\u2net\detect.py", line 113, in load_model
    torch.load(
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\chara\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.`

**Comment by danielgatis** [comment]
https://github.com/danielgatis/rembg/issues/212#issuecomment-1088334962

**Comment by qwerty-qwerty1** [comment]
> [#212 (comment)](https://github.com/danielgatis/rembg/issues/212#issuecomment-1088334962)

How to use alpha matting for all images in a folder and using it in the CLI

**Comment by danielgatis** [comment]
```
rembg p -a -ae 15 path/to/input path/to/output
```

**Comment by qwerty-qwerty1** [comment]
> ```
> rembg p -a -ae 15 path/to/input path/to/output
> ```

Ok, Do you have discord, So I can reach you if I have any doubt
