### ISSUE TITLE
Running setup.py bdist_wheel for llvmlite ... error

### ISSUE THREAD

**Issue by AltayAkkus** [danielgatis/rembg#23]
Hey,
I really like your project! It really saved me a lot of time (and money)
But now I want to install it on a Virtual Machine on Digital Ocean, a Debian 10 one to more exact.
And it doesn't want to install:

```
Building wheels for collected packages: rembg, numba, llvmlite
  Running setup.py bdist_wheel for rembg ... done
  Stored in directory: /root/.cache/pip/wheels/d5/ad/72/a29715e07848809bb37bf068f7540983975e7941fbd4c1ea34
  Running setup.py bdist_wheel for numba ... done
  Stored in directory: /root/.cache/pip/wheels/cd/cd/8c/314cbe49cd8bb876f251763442807db9d55968d1f44cb20013
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pekaldf3/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-u2vc646x --python-tag cp37:
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-pekaldf3/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1

  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built rembg numba
Failed to build llvmlite
Installing collected packages: llvmlite, numba, pymatting, rembg
  Running setup.py install for llvmlite ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pekaldf3/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-i02sowqg/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-install-pekaldf3/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-pekaldf3/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-pekaldf3/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pekaldf3/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-i02sowqg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-pekaldf3/llvmlite/
```

Can anyone help with this? I got a lot of obscure errors I was able to fix (as an example Memory Errors due to torch) but I couldn't fix that one (yet)

**Comment by danielgatis** [comment]
try this before install:

```
pip install --upgrade pip
```

**Comment by AltayAkkus** [comment]
Thanks! This fixed it. Great work
