### ISSUE TITLE
In colab after running with `rembg p`  -  getting this error -- TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by rohan-paul** [danielgatis/rembg#257]
I ran the command `!rembg p /content /content/output` and got below error 

```
Traceback (most recent call last):
  File "/usr/local/bin/rembg", line 5, in <module>
    from rembg.cmd.cli import main
  File "/usr/local/lib/python3.7/dist-packages/rembg/cmd/cli.py", line 7, in <module>
    from ..bg import remove
  File "/usr/local/lib/python3.7/dist-packages/rembg/bg.py", line 67, in <module>
    @functools.lru_cache
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Comment by rohan-paul** [comment]
Kindly Ignore, After I upgraded Colab's Python to 3.9 it was resolved.
