### ISSUE TITLE
Pickling error - _pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by sQur1** [danielgatis/rembg#262]
I'm receiving an error trying to use the rembg module to remove the background of an image. I have all the modules installed as well as torch, torchvision and torchaudio. I'm somewhat of a beginner so I'm not too familiar with pickling, so if somebody could clarify what this error message means or what I can do to fix it, that would be really helpful. Thank you!

```
from rembg.bg import remove
import numpy as np
import io
from PIL import Image

input_path = 'test.png'
output_path = 'out.png'

f = np.fromfile(input_path)
result = remove(f)
img = Image.open(io.BytesIO(result)).convert("RGBA")
img.save(output_path)
```

Running the code, I get the following error:

```
Downloading u2net.pth to /Users/cc/.u2net: 0.00iB [00:00, ?iB/s]
Downloading u2net.pth to /Users/cc/.u2net: 2.21kiB [00:00, 1.86MiB/s]
Traceback (most recent call last):
  File "/Users/cc/Desktop/python_projects/img_to_text/test.py", line 10, in <module>
    result = remove(f)
  File "/Users/cc/Desktop/python_projects/img_to_text/venv/lib/python3.10/site-packages/rembg/bg.py", line 90, in remove
    model = get_model(model_name)
  File "/Users/cc/Desktop/python_projects/img_to_text/venv/lib/python3.10/site-packages/rembg/bg.py", line 78, in get_model
    return detect.load_model(model_name="u2net")
  File "/Users/cc/Desktop/python_projects/img_to_text/venv/lib/python3.10/site-packages/rembg/u2net/detect.py", line 113, in load_model
    torch.load(
  File "/Users/cc/Desktop/python_projects/img_to_text/venv/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/cc/Desktop/python_projects/img_to_text/venv/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by sQur1** [comment]
> 

Created 3.9 in a venv, same error.

```
Downloading u2net.pth to /Users/wiggly/.u2net: 0.00iB [00:00, ?iB/s]
Downloading u2net.pth to /Users/wiggly/.u2net: 2.21kiB [00:00, 2.24MiB/s]
Traceback (most recent call last):
  File "/Users/wiggly/Desktop/python_projects/test2/test.py", line 8, in <module>
    output = remove(input)
  File "/Users/wiggly/Desktop/python_projects/test2/venv/lib/python3.9/site-packages/rembg/bg.py", line 90, in remove
    model = get_model(model_name)
  File "/Users/wiggly/Desktop/python_projects/test2/venv/lib/python3.9/site-packages/rembg/bg.py", line 78, in get_model
    return detect.load_model(model_name="u2net")
  File "/Users/wiggly/Desktop/python_projects/test2/venv/lib/python3.9/site-packages/rembg/u2net/detect.py", line 113, in load_model
    torch.load(
  File "/Users/wiggly/Desktop/python_projects/test2/venv/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/wiggly/Desktop/python_projects/test2/venv/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by danielgatis** [comment]
try to download the models and put them in the folder `~/u2net`.

**Comment by sQur1** [comment]
Do I have to extract the ```u2net.pth``` file? It is in the ```~/u2net``` folder and the results are yet again, the same.
FYI, everytime I create another venv and install rembg then run my script, it says it cannot find matplotlib... It seems like it's a dependancies that hasn't been included in the package.

> try to download the models and put them in the folder `~/u2net`.

**Comment by Prasantkumar987** [comment]
This error comes when the Weights/ Pickle file given is not getting Unpickle. This means your weights are not complete and some problem related to it. Try Downloading weights again it will work.

**Comment by illtellyoulater** [comment]
In my case this was caused by the code downloading this:

https://huggingface.co/erogol/bark/blob/main/text_2.pt (a 16 kb file)

in place of the actual 5 Gb model:

https://huggingface.co/erogol/bark/raw/main/text_2.pt

Of course the code should be able to resolve the second link by using the first one, but it's clearly failing at that for some reason.
