### ISSUE TITLE
undefined symbol: libiconv

### ISSUE THREAD

**Issue by prodemmi** [danielgatis/rembg#277]
**Describe the bug**
When run file that have remove function;I got this error.
In Ubuntu i dont get any error but error is on CentOS 7.

**Expected behavior**
File has to run without any error.

**Error**
`
Traceback (most recent call last):
  File "*/app.py", line 4, in <module>
    from rembg import remove
  File "*/env/lib/python3.8/site-packages/rembg/__init__.py", line 5, in <module>
    from .bg import remove
  File "*/env/lib/python3.8/site-packages/rembg/bg.py", line 6, in <module>
    import onnxruntime as ort
  File "*/env/lib/python3.8/site-packages/onnxruntime/__init__.py", line 34, in <module>
    raise import_capi_exception
  File "*/env/lib/python3.8/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "*/env/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py", line 22, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: /usr/local/lib64/libstdc++.so.6: undefined symbol: libiconv
`

**OS Version:**
CentOS 7

**Rembg version:**
v2.0.21

**Comment by danielgatis** [comment]
try this:

```
yum install glibc-devel
```

**Comment by prodemmi** [comment]
I tried and this is the output:
`Package glibc-devel-2.17-326.el7_9.x86_64 already installed and latest version`
