### ISSUE TITLE
Error on MacOsx 10.14.6

### ISSUE THREAD

**Issue by jrenouard** [danielgatis/rembg#30]
Hello,

Thanks for your code, unfortunately I'm unable to make it work on a Mac.

After installing here's the error I encounter:

>  ✘ julien@mbp-ju-2  ~/Desktop  rembg -p photos
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/rembg", line 5, in <module>
    from rembg.cmd.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rembg/cmd/cli.py", line 7, in <module>
    from ..bg import remove
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rembg/bg.py", line 67, in <module>
    @functools.lru_cache
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

Do you think you can help?

Thanks a lot!

**Comment by danielgatis** [comment]
plz update your python to pyhton 3.8

**Comment by jrenouard** [comment]
Woops, I didn't see the requirements... Thanks!
