### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by deiphi** [danielgatis/rembg#31]
Hello,

I'm unable to make it work on a Windows.

when i exec cmd: rembg -o animal.png animal-3.jpg

`
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\rembg.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\rembg\cmd\cli.py", line 113, in main
    remove(
  File "c:\programdata\anaconda3\lib\site-packages\rembg\bg.py", line 83, in remove
    model = get_model(model_name)
  File "c:\programdata\anaconda3\lib\site-packages\rembg\bg.py", line 72, in get_model
    return detect.load_model(model_name="u2net")
  File "c:\programdata\anaconda3\lib\site-packages\rembg\u2net\detect.py", line 69, in load_model
    net.load_state_dict(torch.load(path))
  File "c:\programdata\anaconda3\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "c:\programdata\anaconda3\lib\site-packages\torch\serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 383141 more bytes. The file might be corrupted.
`

 Thanks a lot!

**Comment by AltayAkkus** [comment]
The image seems to be corrupted, try another one.

**Comment by deiphi** [comment]
It should not be damaged. I used the picture in the example, but it is the same if I change another one.

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\rembg.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\rembg\cmd\cli.py", line 113, in main
    remove(
  File "c:\programdata\anaconda3\lib\site-packages\rembg\bg.py", line 83, in remove
    model = get_model(model_name)
  File "c:\programdata\anaconda3\lib\site-packages\rembg\bg.py", line 72, in get_model
    return detect.load_model(model_name="u2net")
  File "c:\programdata\anaconda3\lib\site-packages\rembg\u2net\detect.py", line 69, in load_model
    net.load_state_dict(torch.load(path))
  File "c:\programdata\anaconda3\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "c:\programdata\anaconda3\lib\site-packages\torch\serialization.py", line 781, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 383141 more bytes. The file might be corrupted.

**Comment by Vishvajeet590** [comment]
> Hello,
> 
> I'm unable to make it work on a Windows.
> 
> when i exec cmd: rembg -o animal.png animal-3.jpg
> 
> `Traceback (most recent call last): File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\ProgramData\Anaconda3\Scripts\rembg.exe\__main__.py", line 7, in <module> File "c:\programdata\anaconda3\lib\site-packages\rembg\cmd\cli.py", line 113, in main remove( File "c:\programdata\anaconda3\lib\site-packages\rembg\bg.py", line 83, in remove model = get_model(model_name) File "c:\programdata\anaconda3\lib\site-packages\rembg\bg.py", line 72, in get_model return detect.load_model(model_name="u2net") File "c:\programdata\anaconda3\lib\site-packages\rembg\u2net\detect.py", line 69, in load_model net.load_state_dict(torch.load(path)) File "c:\programdata\anaconda3\lib\site-packages\torch\serialization.py", line 595, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "c:\programdata\anaconda3\lib\site-packages\torch\serialization.py", line 781, in _legacy_load deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly) RuntimeError: unexpected EOF, expected 383141 more bytes. The file might be corrupted.`
> 
> Thanks a lot!

How did you installed it. It shows 'rembg' is not recognized as an internal or external command,
operable program or batch file.
