### ISSUE TITLE
 Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by pilgrim2go** [danielgatis/rembg#34]
Hi,
I tried following image and got error.

`curl -s https://i.pinimg.com/564x/b0/f2/50/b0f250c4f155a12e916d7ccd46f63bcb.jpg | rembg > output.png`

```
Traceback (most recent call last):
  File "/Users/nowhereman/.pyenv/versions/pydata/bin/rembg", line 6, in <module>
    from rembg.cmd.cli import main
  File "/Users/nowhereman/.pyenv/versions/3.7.3/envs/pydata/lib/python3.7/site-packages/rembg/cmd/cli.py", line 7, in <module>
    from ..bg import remove
  File "/Users/nowhereman/.pyenv/versions/3.7.3/envs/pydata/lib/python3.7/site-packages/rembg/bg.py", line 67, in <module>
    @functools.lru_cache
  File "/Users/nowhereman/.pyenv/versions/3.7.3/lib/python3.7/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

```

Any comment?

**Comment by pilgrim2go** [comment]
Switching to python3.8 resolved the issue.
