### ISSUE TITLE
[BUG] - http server return 422 Unprocessable Entity

### ISSUE THREAD

**Issue by DGrv** [danielgatis/rembg#367]
**Describe the bug**
I would like to use the server as you have in your first tuto video (I guess). Maybe I miss something or do not understand something. Can you help ?

**To Reproduce**

rembg is working properly with `i` and `p` on my machine. 
If I run the server:

```sh
rembg s
```

get the output:

```sh
INFO:     Started server process [29484]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:     127.0.0.1:54521 - "GET / HTTP/1.1" 422 Unprocessable Entity
```

If I open http://127.0.0.1:5000/ or http://localhost:5000/ I see this line only:

`{"detail":[{"loc":["query","url"],"msg":"field required","type":"value_error.missing"}]}`

The http://localhost:5000/docs seems to work

```sh
INFO:     127.0.0.1:54643 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:54643 - "GET /openapi.json HTTP/1.1" 200 OK
```

Should be able to change the parameters on this page ? Because I cannot.

**Expected behavior**
I expect to have a site like yours:

![2022-12-16 14-25-58](https://user-images.githubusercontent.com/15691063/208108452-305ea818-8bbc-4ad3-a728-b796c54b31b9.jpg)

**OS Version:**
Windows 10

**Rembg version:**
rembg                  2.0.29

**Comment by danielgatis** [comment]
try it:

```
http://localhost:5000/?url=http://input.png
```

**Comment by DGrv** [comment]
I think I miss something somewhere...

I have a input.jpg in the folder where I started the `rembg s`

Running your command with input.jpg I get `Internal Server Error`

Am using it wrong or I need to update or fix something ? Thx :)

```sh
INFO:     127.0.0.1:58558 - "GET /?url=http://input.jpg HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\rembg\cli.py", line 421, in get_index
    async with session.get(url) as response:
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 535, in _request
    conn = await self._connector.connect(
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\doria\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host input.jpg:80 ssl:default [getaddrinfo failed]
```

**Comment by amrreko** [comment]
i faced same problem please find solution
