### ISSUE TITLE
[Question]  Running rembg within a container from Lambda

### ISSUE THREAD

**Issue by niteshanandan** [danielgatis/rembg#373]
It looks like some internal dependencies (pooch) that are trying to access a read-only part of the file system. This is prohibited by the lambda runtime and the only ephemeral storage you're allowed to access is the /tmp folder. Was anyone able to get past this?

```
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/task/app.py", line 35, in handler
    output = remove(input)
  File "/var/lang/lib/python3.8/site-packages/rembg/bg.py", line 133, in remove
    session = new_session("u2net")
  File "/var/lang/lib/python3.8/site-packages/rembg/session_factory.py", line 51, in new_session
    pooch.retrieve(
  File "/var/lang/lib/python3.8/site-packages/pooch/core.py", line 224, in retrieve
    make_local_storage(path)
  File "/var/lang/lib/python3.8/site-packages/pooch/utils.py", line 249, in make_local_storage
    os.makedirs(path, exist_ok=True)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
```

**Comment by danielgatis** [comment]
Take a look here:
https://github.com/danielgatis/rembg/blob/main/rembg/session_factory.py#L43-L45

You can download the models and set this env var to point to them.

**Comment by niteshanandan** [comment]
@danielgatis thanks, that did it. For anyone else running into this inside lambdas, hooking it up to an EFS system and updating the env var to point to EFS worked.

**Comment by niteshanandan** [comment]
On second thoughts an easier solution is to point U2NET_HOME to /tmp . No EFS required
