### ISSUE TITLE
[BUG] I can't run the script - error

### ISSUE THREAD

**Issue by Vv-vfx** [danielgatis/rembg#386]
PS D:\rembg_fp>  d:; cd 'd:\rembg_fp'; & 'C:\Users\89252\AppData\Local\Programs\Python\Python39\python.exe' 'c:\Users\89252\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '50584' '--' 'd:\rembg_fp\rm.py'
Traceback (most recent call last):
  File "d:\rembg_fp\rm.py", line 1, in <module>
    from rembg import remove
  File "C:\Users\89252\AppData\Local\Programs\Python\Python39\lib\site-packages\rembg\__init__.py", line 5, in <module>
    from .bg import remove
  File "C:\Users\89252\AppData\Local\Programs\Python\Python39\lib\site-packages\rembg\bg.py", line 6, in <module>
    from cv2 import (
  File "C:\Users\89252\AppData\Local\Programs\Python\Python39\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\89252\AppData\Local\Programs\Python\Python39\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\89252\AppData\Local\Programs\Python\Python39\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\89252\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\89252\AppData\Local\Programs\Python\Python39\lib\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import) 
PS D:\rembg_fp>

**Comment by iTomxy** [comment]
- [module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' #387](https://github.com/Rudrabha/Wav2Lip/issues/387)
- [AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)](https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs)
- [Package | 解决 module ‘cv2‘ has no attribute ‘gapi_wip_gst_GStreamerPipeline‘](https://blog.csdn.net/iLOVEJohnny/article/details/126466515)
- [AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import) #706](https://github.com/asweigart/pyautogui/issues/706)
