### ISSUE TITLE
sudo: rembg：command not found

### ISSUE THREAD

**Issue by tks-reply** [danielgatis/rembg#4]
What a wonderful work!
I am sorry to bother you,but I have a question in "sudo: rembg：command not found".
I have installed rembg,but when I use "rembg -o /home/zc/transformed.png /home/zc/PycharmProjects/pythonProject/modeltest.png",nothing happened.What should I do?How can I operate?

I would very appreciate if you could help me.
Thank you!

**Comment by danielgatis** [comment]
try this

without sudo:
pip install --user rembg

without sudo:
rembg -o ...

**Comment by tks-reply** [comment]
@danielgatis 

Thank you for your timely reply!But when I  do this, it returns an error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fl/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/fl/.local/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fl/.local/lib/python3.6/site-packages/rembg/cmd/cli.py", line 6, in <module>
    from ..bg import remove
  File "/home/fl/.local/lib/python3.6/site-packages/rembg/bg.py", line 8, in <module>
    model_u2net = detect.load_model(model_name="u2net")
  File "/home/fl/.local/lib/python3.6/site-packages/rembg/u2net/detect.py", line 51, in load_model
    path,
  File "/home/fl/.local/lib/python3.6/site-packages/rembg/u2net/detect.py", line 24, in download
    resp = requests.get(url, stream=True)
  File "/home/fl/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/fl/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/fl/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/fl/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/fl/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

How can I solve it?
Looking forward to receiving your reply!
Thank you very much!

**Comment by danielgatis** [comment]
Apparently you are having problems with your internet connection. 

You can download these two files:
https://www.dropbox.com/s/usb1fyiuh8as5gi/u2netp.pth?dl=1
https://www.dropbox.com/s/kdu5mhose1clds0/u2net.pth?dl=1

and put it in "$HOME/.u2net" directory.

**Comment by tks-reply** [comment]
@danielgatis 
Thank you for your timely reply!But when I do this, the same question occurs.

How can I solve it?
Looking forward to receiving your reply!
Thank you very much!

**Comment by danielgatis** [comment]
[![asciicast](https://asciinema.org/a/356139.svg)](https://asciinema.org/a/356139)

**Comment by tks-reply** [comment]
@danielgatis 
Thank you for showing the demo.I have tested in ubuntu without seeing downloading any models,I have put the model in "$HOME/.u2net" directory,but it seems that cannot find rembg in my ubuntu os.Is it available in ubuntu?
I would very appreciate if you could help me,thank you!

**Comment by danielgatis** [comment]
You can try run directly from the module without the binary, like this:

```
python3 -m rembg.cmd.cli -o -o /home/zc/transformed.png /home/zc/PycharmProjects/pythonProject/modeltest.png
```

**Comment by tks-reply** [comment]
@danielgatis 
Thank you for your suggestions!
It is a pity that nothing happens when I use the way to warp the picture,t it seems that cannot find rembg in my ubuntu os.

**Comment by alter-sachin** [comment]
Hey, You might have stopped the dowloading of u2net when you run the rembg command the first time. 
Try deleting the ./u2net folder at your home and you should be good to go.
