### ISSUE TITLE
Unable to install on MacOS Big Sur

### ISSUE THREAD

**Issue by nikhilmufc7** [danielgatis/rembg#42]
Hi , I am trying to install this on MacOS 11.0 (Big sur) it always fails , I have tried different things but it doesn't work
Python version : 3.8.2 , also tried earlier 3.9.0 doesn't work either

Here are my logs:

```Collecting rembg
  Using cached https://files.pythonhosted.org/packages/74/5a/46cbdb14769ed50b1fa16d57e7a34c04d7251afbacdd3589cdfa8ad3503e/rembg-1.0.16.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scikit-image==0.17.2 (from rembg)
  Using cached https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-v7cbgt59/scikit-image/setup.py'"'"'; __file__='"'"'/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-v7cbgt59/scikit-image/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-v7cbgt59/scikit-image/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-v7cbgt59/scikit-image/setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-v7cbgt59/scikit-image/setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
➜  rembg-master git:(master) ✗ curl -s http://input.png | rembg > output.png
zsh: command not found: rembg
➜  rembg-master git:(master) ✗ pip install --upgrade pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages (20.2.4)
➜  rembg-master git:(master) ✗ which python
/usr/bin/python
➜  rembg-master git:(master) ✗ brew uninstall python
Error: No installed keg or cask with the name "python"
➜  rembg-master git:(master) ✗ python --version
Python 2.7.16
➜  rembg-master git:(master) ✗ python3 --version
Python 3.8.2
➜  rembg-master git:(master) ✗ brew reinstall python
Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.0_1.big_
Already downloaded: /Users/nikhilsingh/Library/Caches/Homebrew/downloads/07eae7a7d7ed36eb2ce66e5a1a771df7d9483f58872e38036325d56194554bf8--python@3.9-3.9.0_1.big_sur.bottle.tar.gz
==> Reinstalling python@3.9
==> Pouring python@3.9-3.9.0_1.big_sur.bottle.tar.gz
^C
➜  rembg-master git:(master) ✗ brew reinstall python@3.8
Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Downloading https://homebrew.bintray.com/bottles/python%403.8-3.8.6_1.big_
Already downloaded: /Users/nikhilsingh/Library/Caches/Homebrew/downloads/bc25badd58f2a016a9cf5f45f7ec5b4beb87cba2f01324fbad4a351696738a24--python@3.8-3.8.6_1.big_sur.bottle.tar.gz
==> Reinstalling python@3.8
==> Pouring python@3.8-3.8.6_1.big_sur.bottle.tar.gz
==> /usr/local/Cellar/python@3.8/3.8.6_1/bin/python3 -s setup.py --no-user-cfg
==> /usr/local/Cellar/python@3.8/3.8.6_1/bin/python3 -s setup.py --no-user-cfg
==> /usr/local/Cellar/python@3.8/3.8.6_1/bin/python3 -s setup.py --no-user-cfg
==> Caveats
Python has been installed as
  /usr/local/opt/python@3.8/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  /usr/local/opt/python@3.8/bin/pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

python@3.8 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have python@3.8 first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.zshrc

For compilers to find python@3.8 you may need to set:
  export LDFLAGS="-L/usr/local/opt/python@3.8/lib"

For pkg-config to find python@3.8 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/python@3.8/3.8.6_1: 4,329 files, 69.4MB
➜  rembg-master git:(master) ✗ python --version
Python 2.7.16
➜  rembg-master git:(master) ✗ python3.8
zsh: command not found: python3.8
➜  rembg-master git:(master) ✗ pip3 install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
  Rolling back uninstall of pip
  Moving to /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip-19.2.3.dist-info/
   from /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/~ip-19.2.3.dist-info
  Moving to /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/
   from /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/~ip
  Moving to /Users/nikhilsingh/Library/Caches/com.apple.python/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/
   from /Users/nikhilsingh/Library/Caches/com.apple.python/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/~ip
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
➜  rembg-master git:(master) ✗ pip3 install --upgrade pip --user
Collecting pip
  Using cached https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-20.2.4
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
➜  rembg-master git:(master) ✗ pip3 install --upgrade pip3 --user
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Could not find a version that satisfies the requirement pip3 (from versions: none)
ERROR: No matching distribution found for pip3
➜  rembg-master git:(master) ✗ pip3 install rembg

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting rembg
  Using cached rembg-1.0.16.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy==1.19.4
  Downloading numpy-1.19.4.zip (7.3 MB)
     |████████████████████████████████| 7.3 MB 2.6 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/nikhilsingh/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp2c2qcd32
         cwd: /private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-wsstgq1n/numpy
    Complete output (225 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_philox.pyx
    Processing numpy/random/_bounded_integers.pyx.in
    Processing numpy/random/_sfc64.pyx
    Processing numpy/random/_mt19937.pyx
    Processing numpy/random/bit_generator.pyx
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_pcg64.pyx
    Processing numpy/random/_common.pyx
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
    C compiler: xcrun -sdk macosx clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64

    creating /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/var
    creating /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/var/folders
    creating /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/var/folders/bm
    creating /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn
    creating /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T
    creating /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k
    compile options: '-MMD -MF /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/file.c.d -c'
    xcrun: /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp96fh0k1k/file.c
      libraries mkl_rt not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    accelerate_info:
      libraries accelerate not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
    Library accelerate was not found. Ignoring
      libraries veclib not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
    Library veclib was not found. Ignoring
      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries tatlas,tatlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries satlas,satlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries ptf77blas,ptcblas,atlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries f77blas,cblas,atlas not found in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-10.14.6-x86_64-3.8
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy/distutils
    building library "npymath" sources
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy/core
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npymath
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npymath/npy_math_internal.h
      adding 'build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npymath' to include_dirs.
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npymath/ieee754.c
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npymath/npy_math_complex.c
    None - nothing done with h_files = ['build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npymath/npy_math_internal.h']
    building library "npysort" sources
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common/npy_sort.h
      adding 'build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common' to include_dirs.
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort/quicksort.c
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort/mergesort.c
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort/timsort.c
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort/heapsort.c
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort/radixsort.c
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common/npy_partition.h
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort/selection.c
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common/npy_binsearch.h
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/npysort/binsearch.c
    None - nothing done with h_files = ['build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common/npy_sort.h', 'build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common/npy_partition.h', 'build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/common/npy_binsearch.h']
    building library "npyrandom" sources
    building extension "numpy.core._multiarray_tests" sources
    creating build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/multiarray
    conv_template:> build/src.macosx-10.14.6-x86_64-3.8/numpy/core/src/multiarray/_multiarray_tests.c
    building extension "numpy.core._multiarray_umath" sources
    Running from numpy source directory.
    setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/Users/nikhilsingh/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/nikhilsingh/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/nikhilsingh/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 236, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 508, in <module>
        setup_package()
      File "setup.py", line 500, in setup_package
        setup(**metadata)
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-wsstgq1n/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-wsstgq1n/numpy/numpy/distutils/command/egg_info.py", line 24, in run
        self.run_command("build_src")
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-wsstgq1n/numpy/numpy/distutils/command/build_src.py", line 144, in run
        self.build_sources()
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-wsstgq1n/numpy/numpy/distutils/command/build_src.py", line 161, in build_sources
        self.build_extension_sources(ext)
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-wsstgq1n/numpy/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
        sources = self.generate_sources(sources, ext)
      File "/private/var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/pip-install-wsstgq1n/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 436, in generate_config_h
        moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
      File "numpy/core/setup.py", line 47, in check_types
        out = check_types(*a, **kw)
      File "numpy/core/setup.py", line 292, in check_types
        raise SystemError(
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Users/nikhilsingh/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/bm/8v69908x5q11f27w9ydcn5kh0000gn/T/tmp2c2qcd32 Check the logs for full command output.```

Help appreciated, thanks!

**Comment by arthur-fontaine** [comment]
Just run:
`pip install numpy`

Do that for every dependencies you haven't

**Comment by mario-mtz** [comment]
did you solve your problem? I am having same issue.

**Comment by danielgatis** [comment]
You need to install the python headers file. Try this:

```
xcode-select --install
```
