### ISSUE TITLE
Error when run test code

### ISSUE THREAD

**Issue by VyVu** [danielgatis/rembg#43]
I run cli "rembg -o out.png test.png", console show this error
Traceback (most recent call last):
  File "/home/tony/PycharmProjects/rem/venv/bin/rembg", line 8, in <module>
    sys.exit(main())
  File "/home/tony/PycharmProjects/rem/venv/lib/python3.8/site-packages/rembg/cmd/cli.py", line 118, in main
    remove(
  File "/home/tony/PycharmProjects/rem/venv/lib/python3.8/site-packages/rembg/bg.py", line 84, in remove
    img = Image.open(io.BytesIO(data)).convert("RGB")
  File "/home/tony/PycharmProjects/rem/venv/lib/python3.8/site-packages/PIL/Image.py", line 2943, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f50f7b4eb30>

Please Suggestion. thanks

**Comment by VyVu** [comment]
i closed this issued
