### ISSUE TITLE
[BUG] local variable 'md5' referenced before assignment

### ISSUE THREAD

**Issue by eafpres** [danielgatis/rembg#437]
**Describe the bug**
When trying to use alternative models instead of u2net, setting the model name in a new_session() call causes the error local variable 'md5' referenced before assignment

**To Reproduce**
download isnet-general-use.onnx
put file in ~/user/.u2net folder
chmod -x file to make it not executable

```
from rembg import remove
from rembg.bg import new_session
session = new_session("isnet-general-use")
```
Traceback (most recent call last):

  File "/home/eafpres/.local/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/mnt/c/eaf llc/aa-Analytics and BI/Autonet (Torsten Ostervall)/__pycache__/remove_backgrounds.py", line 44, in <module>
    session = new_session("isnet-general-use")

  File "/home/eafpres/.local/lib/python3.9/site-packages/rembg/session_factory.py", line 49, in new_session
    if hashing.hexdigest() != md5:

UnboundLocalError: local variable 'md5' referenced before assignment

**Expected behavior**
The new_session statement creates a new session to use the isnet-general-use model

**OS Version:**
Ubuntu 20.04 (running in WSL under Windows 11)

**Rembg version:**
rembg.__version__
Out[8]: '2.0.23'

**Additional context**
I tried also for sam, downloaded both files and placed in the directory.  Get a slightly different error:

Traceback (most recent call last):

  File "/home/eafpres/.local/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/mnt/c/eaf llc/aa-Analytics and BI/Autonet (Torsten Ostervall)/__pycache__/remove_backgrounds.py", line 44, in <module>
    session = new_session("sam")

  File "/home/eafpres/.local/lib/python3.9/site-packages/rembg/session_factory.py", line 46, in new_session
    gdown.download(url, str(path), use_cookies=False)

UnboundLocalError: local variable 'url' referenced before assignment

**Comment by eafpres** [comment]
I ran an update pip install -U rembg and this seems to have fixed this issue.
