### ISSUE TITLE
pip install rembg: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by karborator** [danielgatis/rembg#49]
```
 pip install rembg
Collecting rembg
  Using cached rembg-1.0.16.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting waitress==1.4.4
  Using cached waitress-1.4.4-py2.py3-none-any.whl (58 kB)
Collecting numpy==1.19.4
  Using cached numpy-1.19.4-cp39-cp39-win_amd64.whl (13.0 MB)
Collecting scikit-image==0.17.2
  Downloading scikit-image-0.17.2.tar.gz (29.8 MB)
     |████████████████████████████████| 29.8 MB 6.8 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'd:\lab\rembg\rembg-env\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\karbo\\AppData\\Local\\Temp\\pip-install-x23l74te\\scikit-image\\setup.py'"'"'; __file__='"'"'C:\\Users\\karbo\\AppData\\Local\\Temp\\pip-install-x23l74te\\scikit-image\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\karbo\AppData\Local\Temp\pip-pip-egg-info-ic2ueh8m'
         cwd: C:\Users\karbo\AppData\Local\Temp\pip-install-x23l74te\scikit-image\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\karbo\AppData\Local\Temp\pip-install-x23l74te\scikit-image\setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "C:\Users\karbo\AppData\Local\Temp\pip-install-x23l74te\scikit-image\setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.3.1 is available.
You should consider upgrading via the 'd:\lab\rembg\rembg-env\scripts\python.exe -m pip install --upgrade pip' command.
(rembg-env) PS D:\Lab\rembg\rembg-env> python --version
Python 3.9.0
```

![image](https://user-images.githubusercontent.com/5076985/101410266-c6de7280-38e7-11eb-9caf-307b14a7aa12.png)

**Comment by danielgatis** [comment]
```
WARNING: You are using pip version 20.2.3; however, version 20.3.1 is available.
You should consider upgrading via the 'd:\lab\rembg\rembg-env\scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by kirawi** [comment]
https://github.com/numpy/numpy/wiki/FMod-Bug-on-Windows

**Comment by danielgatis** [comment]
```
ModuleNotFoundError: No module named 'numpy'
```

You need to install the numpy module.
