### ISSUE TITLE
Remove function giving error on passing image

### ISSUE THREAD

**Issue by mayhemantt** [danielgatis/rembg#498]
**Describe the bug**
Tried remove the function getting an error

**To Reproduce**

```
from rembg import remove
from PIL import Image

input_path = 'input.jpg' # input image path
output_path = 'output.png' # output image path

input = Image.open(input_path) # load image
output = remove(input) # remove background
output.save(output_path) # save image
```

After running this code getting the following error

**Error**
```
Traceback (most recent call last):
  File "/Users/hemant/Desktop/app-server/server/python/test.py", line 8, in <module>
    output = remove(input) # remove background
  File "/Users/hemant/anaconda3/lib/python3.10/site-packages/rembg/bg.py", line 162, in remove
    session = new_session("u2net", *args, **kwargs)
  File "/Users/hemant/anaconda3/lib/python3.10/site-packages/rembg/session_factory.py", line 26, in new_session
    return session_class(model_name, sess_opts, providers, *args, **kwargs)
  File "/Users/hemant/anaconda3/lib/python3.10/site-packages/rembg/sessions/base.py", line 32, in __init__
    str(self.__class__.download_models(*args, **kwargs)),
  File "/Users/hemant/anaconda3/lib/python3.10/site-packages/rembg/sessions/u2net.py", line 37, in download_models
    pooch.retrieve(
TypeError: retrieve() got an unexpected keyword argument 'progressbar'
```

**tried:** 
`pip install progressbar2`
`pip install progressbar`
`pip install pooch `

**Images**
![image](https://github.com/danielgatis/rembg/assets/62112099/bf19fb7e-6501-468a-91e7-c9b9b016f294)

**OS Version:**
mac m2 pro (16gb)

**Rembg version:**
Did pip install rembg [ig it will install latest stable one]

**Additional context**

**Comment by Qwanties** [comment]
Same issue happened on Ubuntu 22.04 computer with Anaconda Jupyter Notebook. I have tried running in the shell through the CLI option but same issue arises.

**Comment by sandrodevdariani** [comment]
did you guys fix it?

**Comment by sandrodevdariani** [comment]
@danielgatis any help?

**Comment by alfheim1993** [comment]
pip install --upgrade pooch

**Comment by sandrodevdariani** [comment]
thanks man!
