### ISSUE TITLE
Failed to run rembg with onnxruntime-gpu

### ISSUE THREAD

**Issue by jiapei100** [danielgatis/rembg#501]
**Describe the bug**
Failed to run **rembg** with **onnxruntime-gpu**.

**To Reproduce**

1. `pip uninstall onnxruntime`
2. `pip install -U onnxruntime-gpu`
3. `pip install -U rembg`
4. `python test_rembg.py`

**Expected behavior**
Run `test_rembg.py` successfully.

**Images**
N/A

**OS Version:**
Ubuntu 22.04

**Rembg version:**
v2.0.50

**Additional context**
```console
➜  python test_rembg.py
Traceback (most recent call last):
  File "....../test_rembg.py", line 4, in <module>
    from rembg import remove
  File "~/.local/lib/python3.10/site-packages/rembg/__init__.py", line 5, in <module>
    from .bg import remove
  File "~/.local/lib/python3.10/site-packages/rembg/bg.py", line 21, in <module>
    from .session_factory import new_session
  File "~/.local/lib/python3.10/site-packages/rembg/session_factory.py", line 6, in <module>
    from .sessions import sessions_class
  File "~/.local/lib/python3.10/site-packages/rembg/sessions/__init__.py", line 6, in <module>
    from .base import BaseSession
  File "~/.local/lib/python3.10/site-packages/rembg/sessions/base.py", line 10, in <module>
    class BaseSession:
  File "~/.local/lib/python3.10/site-packages/rembg/sessions/base.py", line 14, in BaseSession
    sess_opts: ort.SessionOptions,
AttributeError: module 'onnxruntime' has no attribute 'SessionOptions'
➜  pip show onnxruntime-gpu
Name: onnxruntime-gpu
Version: 1.15.1
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: ~/.local/lib/python3.10/site-packages
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by: rembg
  ~ pip show rembg
Name: rembg
Version: 2.0.50
Summary: Remove image background
Home-page: https://github.com/danielgatis/rembg
Author: Daniel Gatis
Author-email: danielgatis@gmail.com
License: 
Location: ~/.local/lib/python3.10/site-packages
Requires: numpy, onnxruntime, opencv-python-headless, pillow, pooch, pymatting, scikit-image, scipy, tqdm
Required-by: 
➜  ~ python
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime as ort
>>> ort.get_device()
'GPU'
>>> exit()

```

**Comment by jiapei100** [comment]
How to build rembg from source, with **onnxruntime-gpu**???
