### ISSUE TITLE
[BUG]  ImportError: cannot import name 'BORDER_DEFAULT' from 'cv2' (unknown location)

### ISSUE THREAD

**Issue by meetdilip** [danielgatis/rembg#515]
**Describe the bug**

Installed rembg using 

`pip install rembg[gpu,cli] `

I have Nvidia Geforce GTX 1650

and tried

When I tried` $ rembg --help`

got this error

```
$ rembg --help
Traceback (most recent call last):
  File "/home/myPC/.local/bin/rembg", line 5, in <module>
    from rembg.cli import main
  File "/home/myPC/.local/lib/python3.10/site-packages/rembg/__init__.py", line 5, in <module>
    from .bg import remove
  File "/home/myPC/.local/lib/python3.10/site-packages/rembg/bg.py", line 6, in <module>
    from cv2 import (
ImportError: cannot import name 'BORDER_DEFAULT' from 'cv2' (unknown location)

```

**To Reproduce**

1. Go to 'Terminal in Ubuntu 22.04.'
2. Click on 'type ` $ rembg --help` '

**Expected behavior**

rembg help should have worked

**Images**
Input images to reproduce.

**OS Version:**
Ubuntu 22.04

**Rembg version:**

Not sure, just installed using `pip install rembg[gpu,cli] `

**Additional context**
None

**Comment by meetdilip** [comment]
Solved by 

1. Installed Open CV using https://itslinuxfoss.com/guide-install-opencv-ubuntu/
2. https://github.com/danielgatis/rembg/issues/462
