### ISSUE TITLE
No module named 'pymatting_aot.aot' even after installing python38-devel

### ISSUE THREAD

**Issue by arnold408** [danielgatis/rembg#55]
yum install python38-devel
Last metadata expiration check: 1:21:27 ago on Sat 26 Dec 2020 03:52:16 AM UTC.
Package python38-devel-3.8.3-3.module_el8.3.0+468+0c52a667.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 
rembg -o /root/test/test.png /root/test/test.jpg

Failed to import ahead-of-time-compiled modules. This is expected on first import.
Compiling modules and trying again (this might take a minute).
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/PyMatting-1.1.1-py3.8.egg/pymatting_aot/cc.py", line 21, in <module>
    import pymatting_aot.aot
ModuleNotFoundError: No module named 'pymatting_aot.aot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rembg", line 11, in <module>
    load_entry_point('rembg==1.0.17', 'console_scripts', 'rembg')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/rembg-1.0.17-py3.8.egg/rembg/cmd/cli.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/rembg-1.0.17-py3.8.egg/rembg/bg.py", line 6, in <module>
  File "/usr/local/lib/python3.8/site-packages/PyMatting-1.1.1-py3.8.egg/pymatting/__init__.py", line 2, in <module>
    import pymatting_aot.cc
  File "/usr/local/lib/python3.8/site-packages/PyMatting-1.1.1-py3.8.egg/pymatting_aot/cc.py", line 28, in <module>
    compile_modules()
  File "/usr/local/lib/python3.8/site-packages/PyMatting-1.1.1-py3.8.egg/pymatting_aot/cc.py", line 4, in compile_modules
    from numba.pycc import CC
  File "/usr/local/lib/python3.8/site-packages/numba-0.52.0-py3.8-linux-x86_64.egg/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/usr/local/lib/python3.8/site-packages/numba-0.52.0-py3.8-linux-x86_64.egg/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "/usr/local/lib/python3.8/site-packages/llvmlite-0.35.0-py3.8.egg/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/usr/local/lib/python3.8/site-packages/llvmlite-0.35.0-py3.8.egg/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/usr/local/lib/python3.8/site-packages/llvmlite-0.35.0-py3.8.egg/llvmlite/binding/ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so

please help

**Comment by wzxyyqx** [comment]
Hello, have you solved this problem"ModuleNotFoundError: No module named 'pymatting_aot.aot'" yet?

**Comment by arnold408** [comment]
I moved to a new server with more CPU and RAM, script is working

**Comment by Cold-A-Muse** [comment]
> Hello, have you solved this problem"ModuleNotFoundError: No module named 'pymatting_aot.aot'" yet?

Are you trying to run it on a docker image in any case? I had to install a gcc compiler for it to work:
`DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential \ 
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends manpages-dev \`
