### ISSUE TITLE
[BUG] ...ImportError: Pandas requires version '3.1.2' or newer of 'jinja2' (version '3.0.3' currently installed).

### ISSUE THREAD

**Issue by meetdilip** [danielgatis/rembg#563]
**Describe the bug**

Installed pip and rembg CPU Library + CLI

When I tried rembg --help ( after system shutdown and restart in a fairly fresh Ubuntu 22.04) it says

ImportError: Pandas requires version '3.1.2' or newer of 'jinja2' (version '3.0.3' currently installed).

```
Traceback (most recent call last):
  File "/home/myPC/.local/bin/rembg", line 8, in <module>
    sys.exit(main())
  File "/home/myPC/.local/lib/python3.10/site-packages/rembg/cli.py", line 23, in main
    from .commands import command_functions
  File "/home/myPC/.local/lib/python3.10/site-packages/rembg/commands/__init__.py", line 9, in <module>
    module = import_module(f"{__name__}.{module_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/myPC/.local/lib/python3.10/site-packages/rembg/commands/s_command.py", line 8, in <module>
    import gradio as gr
  File "/home/myPC/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/myPC/.local/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/myPC/.local/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/myPC/.local/lib/python3.10/site-packages/gradio/components/__init__.py", line 20, in <module>
    from gradio.components.dataframe import Dataframe
  File "/home/myPC/.local/lib/python3.10/site-packages/gradio/components/dataframe.py", line 12, in <module>
    from pandas.io.formats.style import Styler
  File "/home/myPC/.local/lib/python3.10/site-packages/pandas/io/formats/style.py", line 44, in <module>
    jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
  File "/home/myPC/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 161, in import_optional_dependency
    raise ImportError(msg)
ImportError: Pandas requires version '3.1.2' or newer of 'jinja2' (version '3.0.3' currently installed).
```

**To Reproduce**

1. Go to Terminal
2. Type rembg --help
3. See error

**Expected behavior**

rembg should display help options

**Images**
Input images to reproduce.

**OS Version:**

Ubuntu 22.04 

**Rembg version:**
v2.0.21

**Additional context**

**Comment by meetdilip** [comment]
Used

`pip install -U Jinja2`

**Comment by meetdilip** [comment]
Used

`pip install -U Jinja2`

Now working.
