### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by AzazelHD** [danielgatis/rembg#59]
Please, it is failing. I dont know what is causing the error.

ERROR: Command errored out with exit status 1:
   command: 'c:\users\a\appdata\local\programs\python\python38\python.exe' 'c:\users\a\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\a\AppData\Local\Temp\pip-build-env-j66cn8f3\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\users\a\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\users\a\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\users\a\appdata\local\programs\python\python38\lib\site-packages\pip\__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "c:\users\a\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\main.py", line 5, in <module>
      import locale
    File "c:\users\a\appdata\local\programs\python\python38\lib\locale.py", line 16, in <module>
      import re
    File "c:\users\a\appdata\local\programs\python\python38\lib\re.py", line 145, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\a\appdata\local\programs\python\python38\python.exe' 'c:\users\a\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\a\AppData\Local\Temp\pip-build-env-j66cn8f3\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by danielgatis** [comment]
It is related to your python installation. 
Look at this link:

https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag
