### ISSUE TITLE
Run with error ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by jinwyp** [danielgatis/rembg#61]
Install python 3.8.6 on centos7  and pip install rembg

And run “rembg” show error below

Traceback (most recent call last):
  File "/usr/local/python3/bin/rembg", line 33, in <module>
    sys.exit(load_entry_point('rembg==1.0.18', 'console_scripts', 'rembg')())
  File "/usr/local/python3/bin/rembg", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/python3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/python3/lib/python3.8/site-packages/rembg-1.0.18-py3.8.egg/rembg/cmd/cli.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/python3/lib/python3.8/site-packages/rembg-1.0.18-py3.8.egg/rembg/bg.py", line 11, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/python3/lib/python3.8/site-packages/rembg-1.0.18-py3.8.egg/rembg/u2net/detect.py", line 11, in <module>
  File "/usr/local/python3/lib/python3.8/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import datasets
  File "/usr/local/python3/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 6, in <module>
    from .mnist import MNIST, EMNIST, FashionMNIST, KMNIST, QMNIST
  File "/usr/local/python3/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 11, in <module>
    import lzma
  File "/usr/local/python3/lib/python3.8/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

**Comment by JihyeJung-Work** [comment]
Did you figure out the solution?

**Comment by badboy-tian** [comment]
+1
