### ISSUE TITLE
run error on macOS bigsur

### ISSUE THREAD

**Issue by iusn** [danielgatis/rembg#63]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/rembg", line 5, in <module>
    from rembg.cmd.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rembg/cmd/cli.py", line 7, in <module>
    from ..bg import remove
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rembg/bg.py", line 67, in <module>
    @functools.lru_cache
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/functools.py", line 474, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

Big Sur version is 11.0.1

**Comment by hojel** [comment]
You can skip this error with modifying bg.py, line 67
`@functools.lru_cache(maxsize=None)`
