### ISSUE TITLE
[BUG] Missing dependencies from pypi

### ISSUE THREAD

**Issue by stefsmeets** [danielgatis/rembg#631]
**Describe the bug**

When installing rembg, I get hit with missing dependencies when trying to run the code from the cli. I had to install these packages manually:

- click
- filetype
- asyncer
- gradio
- aiohttp
- watchdog

Afterwards, it worked fine. I didn't find any place like pyproject.toml where rembg declares its dependencies.

**To Reproduce**
```
python -m virtualenv .venv
. .venv/bin/activate
rembg
```

gives

```
Traceback (most recent call last):
  File "/home/stef/python/.venv/bin/rembg", line 5, in <module>
    from rembg.cli import main
  File "/home/stef/python/.venv/lib/python3.12/site-packages/rembg/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Expected behavior**
Works after installing from pypi

**OS Version:**
Fedora 40, python 3.12

**Rembg version:**
v2.0.56

**Additional context**

**Comment by stefsmeets** [comment]
Yep, that's it! Thanks 😅
