### ISSUE TITLE
p switch -w fails with error

### ISSUE THREAD

**Issue by dbucci69** [danielgatis/rembg#659]
Hi, on my linux ubuntu 22.04lts  when I execute this:
`# rembg p -w /in /out`

I got:

```
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2024-07-24 17:26:53.224467889 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:456 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(onnxruntime::python::PySessionOptions&, const ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-07-24 17:26:53.325537055 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/usr/local/bin/rembg", line 5, in <module>
    from rembg.cli import main
  File "/usr/local/lib/python3.10/dist-packages/rembg/cli.py", line 16, in <module>
    _main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rembg/commands/p_command.py", line 191, in p_command
    for each_input in inputs_tqdm:
UnboundLocalError: local variable 'inputs_tqdm' referenced before assignment
```
Can someone has same issue, can you correct this? Thank you

**Comment by dbucci69** [comment]
looking at line 191 in /usr/local/lib/python3.10/dist-packages/rembg/commands/p_command.py I patched the code indenting the for loop inside the previous if, resulting in this:

```
    if not watch:
        inputs_tqdm = tqdm(inputs)

        for each_input in inputs_tqdm:
            if not each_input.is_dir():
                process(each_input)

    if watch:
        should_watch = True
        observer = Observer()


```
