### ISSUE TITLE
Install numpy 1.19.4 error on Windows，Could you update to 1.19.3 or 1.19.5？

### ISSUE THREAD

**Issue by jinwyp** [danielgatis/rembg#72]
run rembg on windows got error

···
Traceback (most recent call last):
  File "d:\github\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\github\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\github\python38\Scripts\rembg.exe\__main__.py", line 4, in <module>
  File "d:\github\python38\lib\site-packages\rembg\cmd\cli.py", line 9, in <module>
    from ..bg import remove
  File "d:\github\python38\lib\site-packages\rembg\bg.py", line 4, in <module>
    import numpy as np
  File "d:\github\python38\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "d:\github\python38\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('d:\\github\\python38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
···

Could you update requirements.txt with numpy  1.19.3 or 1.19.5 ？

https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html?page=2&pageSize=10&sort=votes&type=problem

**Comment by danielgatis** [comment]
done
