### ISSUE TITLE
"Using as a docker" doesn't work

### ISSUE THREAD

**Issue by the-devil-you-know** [danielgatis/rembg#88]
Run the command: `curl -s https://bellard.org/bpg/2.png | sudo docker run -i -v ~/.u2net:/root/.u2net danielgatis/rembg:latest > output.png`

Result:
`
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/usr/local/bin/rembg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/rembg/cmd/cli.py", line 118, in main
    remove(
  File "/usr/local/lib/python3.8/dist-packages/rembg/bg.py", line 83, in remove
    model = get_model(model_name)
  File "/usr/local/lib/python3.8/dist-packages/rembg/bg.py", line 72, in get_model
    return detect.load_model(model_name="u2net")
  File "/usr/local/lib/python3.8/dist-packages/rembg/u2net/detect.py", line 72, in load_model
    net.load_state_dict(torch.load(path, map_location="cpu",))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
`

**Comment by ansnoussi** [comment]
same issue here, @the-devil-you-know  have you found a solution yet ?

**Comment by the-devil-you-know** [comment]
@ansnoussi no, i decided to use another library, https://github.com/the-devil-you-know/image-background-remove-tool/tree/nontested **nontested** branch has a docker implementation.

**Comment by ansnoussi** [comment]
great, thanks for sharing this @the-devil-you-know .
