### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by MousaSoutari** [danielgatis/rembg#89]
when trying to use it  "rembg -o source destination"
Traceback (most recent call last):
  File "c:\users\mousa\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mousa\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mousa\AppData\Local\Programs\Python\Python39\Scripts\rembg.exe\__main__.py", line 4, in <module>
  File "c:\users\mousa\appdata\local\programs\python\python39\lib\site-packages\rembg\cmd\cli.py", line 9, in <module>
    from ..bg import remove
  File "c:\users\mousa\appdata\local\programs\python\python39\lib\site-packages\rembg\bg.py", line 5, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by danielgatis** [comment]
you need to install the PIL module.
