### ISSUE TITLE
Error in functools.py on Google Colab

### ISSUE THREAD

**Issue by jtremback** [danielgatis/rembg#93]
When running this tool in Google Colab, I received the following error:

```
!rembg -o /content/amethyst_000000005_output.png /content/amethyst_000000005.png
```

```
Traceback (most recent call last):
  File "/usr/local/bin/rembg", line 5, in <module>
    from rembg.cmd.cli import main
  File "/usr/local/lib/python3.7/dist-packages/rembg/cmd/cli.py", line 7, in <module>
    from ..bg import remove
  File "/usr/local/lib/python3.7/dist-packages/rembg/bg.py", line 67, in <module>
    @functools.lru_cache
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

I was able to fix this error by navigating to `/usr/local/lib/python3.7/dist-packages/rembg/bg.py` and commenting out line 67.

**Comment by danielgatis** [comment]
```
Requirements
python 3.8 or newer
```
